### PR TITLE
youtube-downloader : Update 1.1 (Major Enhancement)

### PR DESCRIPTION
**Pull request by Yashwanth-Kumar-Kurakula**
Change Log:

1. Complete change of code while simultaneously enhancing the functionality and adding UI to the application.
2. Tkinter was used to create simple yet powerful GUI for Users.
3. Added a button where the user can input his own custom file path instead of using a static File path.
4. Retained the Progressbar feature in Tkinter using ttk ProgressBar .
5. Optimized the UI and padding of the elements to make it look cleaner.
6. Added a Error message when Invalid input is provided by the user.
7. Modified the list of Contributors

### CODE REVIEW

**Comment by timotheeMM** [comment]
Hi @Yashwanth-Kumar-Kurakula!
Thank you so much for your work, but I would like you to change a few things:
* I would like to keep the command line version and place it in a CLI folder.
* Your GUI version would be in another folder GUI.
* The architecture would be like that:
______ src (folder)
____________ main.py (file)
____________ cli (folder)
__________________ cli.py (file)
____________ gui (folder)
__________________ gui.py (file)
* In the main.py file, there would be a command line text like “type 1 for the command line and 2 for the graphical interface”. Depending on the result, either we call the function contained in the file cli.py or gui.py.

* For GUI: center the message “download success”, the beginning of phase “enter the URL…” is too close to the edge.
* Put docstring in the code.
* For the CONTRIBUTORS.md file. I want the phrase “put your name here” on top, so people see it first, like that:
image
Thank you in advance!

**Comment by Yashwanth-Kumar-Kurakula** [comment]
Hi @timotheeMM !
Thank you for your response. I have acknowledged your requirements, and I am currently in the process of implementing the requested changes.

 I do, however, have a question. Would it be acceptable to merge the pull request with Update 1.1, and designate your requested changes as Update 1.2 in a separate pull request? Alternatively, would you prefer that I close this pull request and create a new one encompassing all the requested changes? I should mention that I am a novice programmer who recently started using GitHub a few days ago, and I am keen on learning how things work here. I eagerly await your guidance. Thank you in advance.

**Comment by timotheeMM** [comment]
@Yashwanth-Kumar-Kurakula 
Don’t worry, I’m a beginner too. :blush:
A few weeks ago, I was unable to distinguish git from GitHub. :laughing:
I advise you to close this pull request and reopen a new one.
Thank you for your work.

**Comment by Yashwanth-Kumar-Kurakula** [comment]
Hi @timotheeMM !. I apologize for the delay in development. Unfortunately, I had some unexpected personal matters that required my attention. I will make it a priority to implement the changes by the end of this week.

**Comment by timotheeMM** [comment]
Ok. No problem!

**Pull request closed without merging**
